const AUTH_CLEAR = 'auth/CLEAR',
  AUTH_DISCARD = 'auth/DISCARD',
  AUTH_FAIL = 'auth/FAIL',
  AUTH_SUCCESS = 'auth/SUCCESS',
  AUTH_HASH = 463258776,
  // Layout Constants
  LAYOUT_DRAWER_CLOSED = 'layout/DRAWER_CLOSED',
  LAYOUT_DRAWER_OPEN = 'layout/DRAWER_OPEN',
  LAYOUT_LIST_MENU_VISIBLE = 'layout/LIST_MENU_VISIBLE',
  LAYOUT_LIST_MENU_HIDDEN = 'layout/LIST_MENU_HIDDEN',
  LAYOUT_LIST_MENU_SET_ANCHOR_EL = 'layout/LIST_MENU_SET_ANCHOR_EL',
  LAYOUT_LIST_MENU_CLEAR_ANCHOR_EL = 'layout/LIST_MENU_CLEAR_ANCHOR_EL',
  LAYOUT_MORE_MENU_SET_ANCHOR_EL = 'layout/MORE_MENU_SET_ANCHOR_EL',
  LAYOUT_MORE_MENU_CLEAR_ANCHOR_EL = 'layout/MORE_MENU_CLEAR_ANCHOR_EL',
  LAYOUT_OPEN_CLOSE_THEME_DRAWER = 'layout/OPEN_CLOSE_THEME_DRAWER',
  LAYOUT_HIDDEN = 'hidden',
  LAYOUT_VISIBLE = 'visible',
  LAYOUT_ABOUT_CLOSE = 'layout/ABOUT_CLOSE',
  LAYOUT_ABOUT_OPEN = 'layout/ABOUT_OPEN',
  LAYOUT_CHANGE_TAB = 'layout/CHANGE_TAB',
  LAYOUT_ADD_USER_TOGGLE = 'layout/ADD_USER_OPEN',
  // Theme Constants
  THEME_DARK = 'dark',
  THEME_LIGHT = 'light',
  THEME_ADD_AVAILABLE = 'theme/ADD_AVAILABLE',
  THEME_DARK_MODE = 'theme/DARK_MODE',
  THEME_PALETTE_SELECTED = 'theme/PALETTE_SELECTED',
  THEME_SET_PRIMARY = 'theme/SET_PRIMARY',
  THEME_SET_SECONDARY = 'theme/SET_SECONDARY',
  HASH_CODE = str => {
    let hash = 0,
      len = str.length,
      chr;

    if (len > 0)
      for (let i = 0; i < len; i++) {
        chr = str.charCodeAt(i);
        hash = (hash << 5) - hash + chr;
        hash |= 0; // Convert to 32bit integer
      }

    return hash;
  };

export {
  AUTH_CLEAR,
  AUTH_DISCARD,
  AUTH_FAIL,
  AUTH_SUCCESS,
  AUTH_HASH,
  LAYOUT_DRAWER_CLOSED,
  LAYOUT_DRAWER_OPEN,
  LAYOUT_LIST_MENU_VISIBLE,
  LAYOUT_LIST_MENU_HIDDEN,
  LAYOUT_LIST_MENU_SET_ANCHOR_EL,
  LAYOUT_LIST_MENU_CLEAR_ANCHOR_EL,
  LAYOUT_MORE_MENU_SET_ANCHOR_EL,
  LAYOUT_MORE_MENU_CLEAR_ANCHOR_EL,
  LAYOUT_OPEN_CLOSE_THEME_DRAWER,
  LAYOUT_HIDDEN,
  LAYOUT_VISIBLE,
  LAYOUT_ABOUT_CLOSE,
  LAYOUT_ABOUT_OPEN,
  LAYOUT_CHANGE_TAB,
  LAYOUT_ADD_USER_TOGGLE,
  THEME_DARK,
  THEME_LIGHT,
  THEME_ADD_AVAILABLE,
  THEME_DARK_MODE,
  THEME_PALETTE_SELECTED,
  THEME_SET_PRIMARY,
  THEME_SET_SECONDARY,
  HASH_CODE
};
