const AUTH_CLEAR = 'auth/CLEAR',
  AUTH_DISCARD = 'auth/DISCARD',
  AUTH_FAIL = 'auth/FAIL',
  AUTH_SUCCESS = 'auth/SUCCESS',
  AUTH_HASH = 463258776,
  LAYOUT_DRAWER_CLOSED = 'layout/DRAWER_CLOSED',
  LAYOUT_DRAWER_OPEN = 'layout/DRAWER_OPEN',
  LAYOUT_LIST_MENU_VISIBLE = 'layout/LIST_MENU_VISIBLE',
  LAYOUT_LIST_MENU_HIDDEN = 'layout/LIST_MENU_HIDDEN',
  LAYOUT_LIST_MENU_SET_ANCHOR_EL = 'layout/LIST_MENU_SET_ANCHOR_EL',
  LAYOUT_LIST_MENU_CLEAR_ANCHOR_EL = 'layout/LIST_MENU_CLEAR_ANCHOR_EL',
  LAYOUT_MORE_MENU_SET_ANCHOR_EL = 'layout/MORE_MENU_SET_ANCHOR_EL',
  LAYOUT_MORE_MENU_CLEAR_ANCHOR_EL = 'layout/MORE_MENU_CLEAR_ANCHOR_EL',
  LAYOUT_HIDDEN = 'hidden',
  LAYOUT_VISIBLE = 'visible',
  HASH_CODE = str => {
    let hash = 0,
      len = str.length,
      chr;

    if (len > 0)
      for (let i = 0; i < len; i++) {
        chr = str.charCodeAt(i);
        hash = (hash << 5) - hash + chr;
        hash |= 0; // Convert to 32bit integer
      }

    return hash;
  };

export {
  AUTH_CLEAR,
  AUTH_DISCARD,
  AUTH_FAIL,
  AUTH_SUCCESS,
  AUTH_HASH,
  LAYOUT_DRAWER_CLOSED,
  LAYOUT_DRAWER_OPEN,
  LAYOUT_LIST_MENU_VISIBLE,
  LAYOUT_LIST_MENU_HIDDEN,
  LAYOUT_LIST_MENU_SET_ANCHOR_EL,
  LAYOUT_LIST_MENU_CLEAR_ANCHOR_EL,
  LAYOUT_MORE_MENU_SET_ANCHOR_EL,
  LAYOUT_MORE_MENU_CLEAR_ANCHOR_EL,
  LAYOUT_HIDDEN,
  LAYOUT_VISIBLE,
  HASH_CODE
};
