const AUTH_BUSY = 'auth/BUSY',
  AUTH_CLEAR = 'auth/CLEAR',
  AUTH_DISABLED = 'auth/DISABLED',
  AUTH_DISCARD = 'auth/DISCARD',
  AUTH_FAIL = 'auth/FAIL',
  AUTH_SUCCESS = 'auth/SUCCESS',
  // Data Constants
  DATA_CLEAR_ERROR = 'data/CLEAR_ERROR',
  DATA_CLEAR_UNDO = 'data/CLEAR_UNDO',
  DATA_ERROR = 'data/ERROR',
  DATA_ADD_USER = 'data/ADD_USER',
  DATA_REMOVE_USER = 'data/REMOVE_USER',
  DATA_UNDO_REMOVE_USER = 'data/UNDO_REMOVE_USER',
  DATA_USER = 'data/USER',
  DATA_USERS = 'data/USERS',
  // Layout Constants
  LAYOUT_DRAWER_CLOSED = 'layout/DRAWER_CLOSED',
  LAYOUT_DRAWER_OPEN = 'layout/DRAWER_OPEN',
  LAYOUT_LIST_MENU_VISIBLE = 'layout/LIST_MENU_VISIBLE',
  LAYOUT_LIST_MENU_HIDDEN = 'layout/LIST_MENU_HIDDEN',
  LAYOUT_LIST_MENU_SET_ANCHOR_EL = 'layout/LIST_MENU_SET_ANCHOR_EL',
  LAYOUT_LIST_MENU_CLEAR_ANCHOR_EL = 'layout/LIST_MENU_CLEAR_ANCHOR_EL',
  LAYOUT_MORE_MENU_SET_ANCHOR_EL = 'layout/MORE_MENU_SET_ANCHOR_EL',
  LAYOUT_MORE_MENU_CLEAR_ANCHOR_EL = 'layout/MORE_MENU_CLEAR_ANCHOR_EL',
  LAYOUT_HIDDEN = 'hidden',
  LAYOUT_VISIBLE = 'visible',
  LAYOUT_CHANGE_TAB = 'layout/CHANGE_TAB',
  // Theme Constants
  THEME_DARK = 'dark',
  THEME_LIGHT = 'light',
  THEME_SET_AVAILABLE = 'theme/SET_AVAILABLE',
  THEME_DARK_MODE = 'theme/DARK_MODE',
  THEME_PALETTE_SELECTED = 'theme/PALETTE_SELECTED',
  THEME_SET_PRIMARY = 'theme/SET_PRIMARY',
  THEME_SET_SECONDARY = 'theme/SET_SECONDARY',
  ADD_USER_FORM_NAME = 'add',
  BUSY_DELAY = 400,
  USER_MENU_ID = 'userMenu',
  HASH_CODE = str => {
    let hash = 0,
      len = str.length,
      chr;

    if (len > 0)
      for (let i = 0; i < len; i++) {
        chr = str.charCodeAt(i);
        hash = (hash << 5) - hash + chr;
        hash |= 0; // Convert to 32bit integer
      }

    return hash;
  };

export {
  AUTH_BUSY,
  AUTH_CLEAR,
  AUTH_DISABLED,
  AUTH_DISCARD,
  AUTH_FAIL,
  AUTH_SUCCESS,
  DATA_CLEAR_ERROR,
  DATA_CLEAR_UNDO,
  DATA_ERROR,
  DATA_ADD_USER,
  DATA_REMOVE_USER,
  DATA_UNDO_REMOVE_USER,
  DATA_USER,
  DATA_USERS,
  LAYOUT_DRAWER_CLOSED,
  LAYOUT_DRAWER_OPEN,
  LAYOUT_LIST_MENU_VISIBLE,
  LAYOUT_LIST_MENU_HIDDEN,
  LAYOUT_LIST_MENU_SET_ANCHOR_EL,
  LAYOUT_LIST_MENU_CLEAR_ANCHOR_EL,
  LAYOUT_MORE_MENU_SET_ANCHOR_EL,
  LAYOUT_MORE_MENU_CLEAR_ANCHOR_EL,
  LAYOUT_HIDDEN,
  LAYOUT_VISIBLE,
  LAYOUT_CHANGE_TAB,
  THEME_DARK,
  THEME_LIGHT,
  THEME_SET_AVAILABLE,
  THEME_DARK_MODE,
  THEME_PALETTE_SELECTED,
  THEME_SET_PRIMARY,
  THEME_SET_SECONDARY,
  ADD_USER_FORM_NAME,
  BUSY_DELAY,
  USER_MENU_ID,
  HASH_CODE
};
